 INSERT INTO occurrencecodes (id, code, description) VALUES (0, 0, 'Processo de Transporte já Iniciado');
INSERT INTO occurrencecodes (id, code, description) VALUES (1, 1, 'Entrega Realizada Normalmente');
INSERT INTO occurrencecodes (id, code, description) VALUES (2, 2, 'Entrega Fora da Data Programada');
INSERT INTO occurrencecodes (id, code, description) VALUES (3, 3, 'Recusa por Falta de Pedido de Compra');
INSERT INTO occurrencecodes (id, code, description) VALUES (4, 4, 'Recusa por Pedido de Compra Cancelado');
INSERT INTO occurrencecodes (id, code, description) VALUES (5, 5, 'Falta de Espaço Físico no Depósito do Cliente Destino');
INSERT INTO occurrencecodes (id, code, description) VALUES (6, 6, 'Endereço do Cliente Destino não Localizado');
INSERT INTO occurrencecodes (id, code, description) VALUES (7, 7, 'Devolução não Autorizada pelo Cliente');
INSERT INTO occurrencecodes (id, code, description) VALUES (8, 8, 'Preço Mercadoria em Desacordo com o Pedido Compra');
INSERT INTO occurrencecodes (id, code, description) VALUES (9, 9, 'Mercadoria em Desacordo com o Pedido Compra');
INSERT INTO occurrencecodes (id, code, description) VALUES (10, 10, 'Cliente Destino somente Recebe Mercadoria com Frete Pago');
INSERT INTO occurrencecodes (id, code, description) VALUES (11, 11, 'Recusa por Deficiência Embalagem Mercadoria');
INSERT INTO occurrencecodes (id, code, description) VALUES (12, 12, 'Redespacho não Indicado');
INSERT INTO occurrencecodes (id, code, description) VALUES (13, 13, 'Transportadora não Atende a Cidade do Cliente Destino');
INSERT INTO occurrencecodes (id, code, description) VALUES (14, 14, 'Embalagem Sinistrada');
INSERT INTO occurrencecodes (id, code, description) VALUES (15, 15, 'Embalagem Sinistrada');
INSERT INTO occurrencecodes (id, code, description) VALUES (16, 16, 'Pedido de Compras em Duplicidade');
INSERT INTO occurrencecodes (id, code, description) VALUES (17, 17, 'Mercadoria fora da Embalagem de Atacadista');
INSERT INTO occurrencecodes (id, code, description) VALUES (18, 18, 'Mercadorias Trocadas');
INSERT INTO occurrencecodes (id, code, description) VALUES (19, 19, 'Reentrega Solicitada pelo Cliente');
INSERT INTO occurrencecodes (id, code, description) VALUES (20, 20, 'Entrega Prejudicada por Horário/Falta de Tempo Hábil');
INSERT INTO occurrencecodes (id, code, description) VALUES (21, 21, 'Estabelecimento Fechado');
INSERT INTO occurrencecodes (id, code, description) VALUES (22, 22, 'Reentrega sem Cobrança do Cliente');
INSERT INTO occurrencecodes (id, code, description) VALUES (23, 23, 'Extravio de Mercadoria em Trânsito');
INSERT INTO occurrencecodes (id, code, description) VALUES (24, 24, 'Mercadoria Reentregue ao Cliente Destino');
INSERT INTO occurrencecodes (id, code, description) VALUES (25, 25, 'Mercadoria Devolvida ao Cliente de Origem');
INSERT INTO occurrencecodes (id, code, description) VALUES (26, 26, 'Nota Fiscal Retida pela Fiscalização');
INSERT INTO occurrencecodes (id, code, description) VALUES (27, 27, 'Roubo de Carga');
INSERT INTO occurrencecodes (id, code, description) VALUES (28, 28, 'Mercadoria Retida até Segunda Ordem');
INSERT INTO occurrencecodes (id, code, description) VALUES (29, 29, 'Cliente Retira Mercadoria na Transportadora');
INSERT INTO occurrencecodes (id, code, description) VALUES (30, 30, 'Problema com a Documentação (Nota Fiscal e/ou CTRC)');
INSERT INTO occurrencecodes (id, code, description) VALUES (31, 31, 'Entrega com Indenização Efetuada');
INSERT INTO occurrencecodes (id, code, description) VALUES (32, 32, 'Falta com Solicitação de Reposição');
INSERT INTO occurrencecodes (id, code, description) VALUES (33, 33, 'Falta com Busca/Reconferência');
INSERT INTO occurrencecodes (id, code, description) VALUES (34, 34, 'Cliente Fechado para Balanço');
INSERT INTO occurrencecodes (id, code, description) VALUES (35, 35, 'Quantidade de Produto em Desacordo (Nota Fiscal e/ou Pedido)');
INSERT INTO occurrencecodes (id, code, description) VALUES (36, 36, 'Extravio de documentos pela cia. Aérea – Cód. Transp. Aéreo');
INSERT INTO occurrencecodes (id, code, description) VALUES (37, 37, 'Extravio de carga pela cia. Aérea – Cód. Transp. Aéreo');
INSERT INTO occurrencecodes (id, code, description) VALUES (38, 38, 'Avaria de carga pela cia. Aérea – Cód. Transp. Aéreo');
INSERT INTO occurrencecodes (id, code, description) VALUES (39, 39, 'Corte de carga na pista – Cód. Transp. Aéreo');
INSERT INTO occurrencecodes (id, code, description) VALUES (40, 40, 'Aeroporto fechado na origem – Cód. Transp. Aéreo');
INSERT INTO occurrencecodes (id, code, description) VALUES (41, 41, 'Pedido de Compra Incompleto');
INSERT INTO occurrencecodes (id, code, description) VALUES (42, 42, 'Nota Fiscal com Produtos de Setores Diferentes');
INSERT INTO occurrencecodes (id, code, description) VALUES (43, 43, 'Feriado Local/Nacional');
INSERT INTO occurrencecodes (id, code, description) VALUES (44, 44, 'Excesso de Veículos');
INSERT INTO occurrencecodes (id, code, description) VALUES (45, 45, 'Cliente Destino Encerrou Atividades');
INSERT INTO occurrencecodes (id, code, description) VALUES (46, 46, 'Responsável de Recebimento Ausente');
INSERT INTO occurrencecodes (id, code, description) VALUES (47, 47, 'Cliente Destino em Greve');
INSERT INTO occurrencecodes (id, code, description) VALUES (48, 48, 'Aeroporto fechado no destino – Cód. Transp. Aéreo');
INSERT INTO occurrencecodes (id, code, description) VALUES (49, 49, 'Voo cancelado – Cód. Transp. Aéreo');
INSERT INTO occurrencecodes (id, code, description) VALUES (50, 50, 'Greve nacional (Greve Geral)');
INSERT INTO occurrencecodes (id, code, description) VALUES (51, 51, 'Mercadoria Vencida (Data de Validade Expirada)');
INSERT INTO occurrencecodes (id, code, description) VALUES (52, 52, 'Mercadoria não foi Embarcada, Permanecendo na Origem');
INSERT INTO occurrencecodes (id, code, description) VALUES (53, 53, 'Mercadoria não foi Embarcada, Permanecendo na Origem');
INSERT INTO occurrencecodes (id, code, description) VALUES (54, 54, 'Mercadoria Embarcada sem Conhecimento/Conhecimento não Embarcado');
INSERT INTO occurrencecodes (id, code, description) VALUES (55, 55, 'Endereço de Transportadora de Redespacho não Localizado/Informado');
INSERT INTO occurrencecodes (id, code, description) VALUES (56, 56, 'Cliente não Aceita Mercadoria com Pagamento de Reembolso');
INSERT INTO occurrencecodes (id, code, description) VALUES (57, 57, 'Transportadora não Atende a Cidade da Transportadora de Redespacho');
INSERT INTO occurrencecodes (id, code, description) VALUES (58, 58, 'Quebra do Veiculo de Entrega');
INSERT INTO occurrencecodes (id, code, description) VALUES (59, 59, 'Cliente sem Verba para Pagar o Frete');
INSERT INTO occurrencecodes (id, code, description) VALUES (60, 60, 'Endereço de Entrega Errado');
INSERT INTO occurrencecodes (id, code, description) VALUES (61, 61, 'Cliente sem Verba para Reembolso');
INSERT INTO occurrencecodes (id, code, description) VALUES (62, 62, 'Recusa da Carga por Valor de Frete Errado');
INSERT INTO occurrencecodes (id, code, description) VALUES (63, 63, 'Identificação do Cliente não Informada/Enviada/Insuficiente');
INSERT INTO occurrencecodes (id, code, description) VALUES (64, 64, 'Cliente não Identificado/Cadastrado');
INSERT INTO occurrencecodes (id, code, description) VALUES (65, 65, 'Entrar em Contato com o Comprador');
INSERT INTO occurrencecodes (id, code, description) VALUES (66, 66, 'Troca não Disponível');
INSERT INTO occurrencecodes (id, code, description) VALUES (67, 67, 'Fins Estatísticos');
INSERT INTO occurrencecodes (id, code, description) VALUES (68, 68, 'Data de Entrega Diferente do Pedido');
INSERT INTO occurrencecodes (id, code, description) VALUES (69, 69, 'Substituição Tributária');
INSERT INTO occurrencecodes (id, code, description) VALUES (70, 70, 'Sistema Fora do Ar');
INSERT INTO occurrencecodes (id, code, description) VALUES (71, 71, 'Cliente Destino não Recebe Pedido Parcial');
INSERT INTO occurrencecodes (id, code, description) VALUES (72, 72, 'Cliente Destino só Recebe Pedido Parcial');
INSERT INTO occurrencecodes (id, code, description) VALUES (73, 73, 'Redespacho somente com Frete Pago');
INSERT INTO occurrencecodes (id, code, description) VALUES (74, 74, 'Funcionário não autorizado a Receber Mercadorias');
INSERT INTO occurrencecodes (id, code, description) VALUES (75, 75, 'Mercadoria Embarcada para Rota Indevida');
INSERT INTO occurrencecodes (id, code, description) VALUES (76, 76, 'Estrada/Entrada de Acesso Interditada');
INSERT INTO occurrencecodes (id, code, description) VALUES (77, 77, 'Cliente Destino Mudou de Endereço');
INSERT INTO occurrencecodes (id, code, description) VALUES (78, 78, 'Avaria Total');
INSERT INTO occurrencecodes (id, code, description) VALUES (79, 79, 'Avaria Parcial');
INSERT INTO occurrencecodes (id, code, description) VALUES (80, 80, 'Extravio Total');
INSERT INTO occurrencecodes (id, code, description) VALUES (81, 81, 'Extravio Parcial');
INSERT INTO occurrencecodes (id, code, description) VALUES (82, 82, 'Sobra de Mercadoria sem Nota Fiscal');
INSERT INTO occurrencecodes (id, code, description) VALUES (83, 83, 'Mercadoria em poder da SUFRAMA para Internação');
INSERT INTO occurrencecodes (id, code, description) VALUES (84, 84, 'Mercadoria Retirada para Conferência');
INSERT INTO occurrencecodes (id, code, description) VALUES (85, 85, 'Apreensão Fiscal da Mercadoria');
INSERT INTO occurrencecodes (id, code, description) VALUES (86, 86, 'Excesso de Carga/Peso');
INSERT INTO occurrencecodes (id, code, description) VALUES (87, 87, 'Férias Coletivas');
INSERT INTO occurrencecodes (id, code, description) VALUES (88, 88, 'Recusado, aguardando negociação');
INSERT INTO occurrencecodes (id, code, description) VALUES (89, 89, 'Aguardando refaturamento das mercadorias');
INSERT INTO occurrencecodes (id, code, description) VALUES (90, 90, 'Recusado pelo Redespachante');
INSERT INTO occurrencecodes (id, code, description) VALUES (91, 91, 'Entrega Programada');
INSERT INTO occurrencecodes (id, code, description) VALUES (92, 92, 'Problemas Fiscais');
INSERT INTO occurrencecodes (id, code, description) VALUES (93, 93, 'Aguardando carta de correção');
INSERT INTO occurrencecodes (id, code, description) VALUES (94, 94, 'Recusa por divergência nas condições de pagamento');
INSERT INTO occurrencecodes (id, code, description) VALUES (95, 95, 'Carga aguardando vôo conexão – Cód. Transp. Aéreo');
INSERT INTO occurrencecodes (id, code, description) VALUES (96, 96, 'Carga sem embalagem própria para transp. Aéreo – Cód. Transp. Aéreo');
INSERT INTO occurrencecodes (id, code, description) VALUES (97, 97, 'Carga com dimensão superior ao porão da aeronave – Cód. Transp. Aéreo');
INSERT INTO occurrencecodes (id, code, description) VALUES (98, 98, 'Chegada na cidade ou filial de destino');
INSERT INTO occurrencecodes (id, code, description) VALUES (99, 99, 'Outros tipos de ocorrências não especificados acima');